# Generated by Django 6.0.5 on 2026-05-16 18:58

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('1', 'Танки'), ('2', 'Хилы'), ('3', 'ДД'), ('4', 'Торговцы'), ('5', 'Гилдмастеры'), ('6', 'Квестгиверы'), ('7', 'Кузнецы'), ('8', 'Кожевники'), ('9', 'Зельевары'), ('10', 'Мастера заклинаний')])),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_date', models.DateTimeField(auto_now_add=True)),
                ('resp_content', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('resp_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resp_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
    ]
