# Generated by Django 5.2.7 on 2026-05-22 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='resp_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='board.post'),
        ),
    ]
